spring:
  application:
    name: backend

  web:
    resources:
      static-locations: "file:/app/static/,classpath:/static/"

  datasource:
    url: jdbc:sqlite:${ASSOINCLOUD_DB_PATH:./data/assoincloud.db}
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    locations: classpath:db/migration

  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB

assoincloud:
  password: ${ASSOINCLOUD_PASSWORD:}
  documents:
    root: ${ASSOINCLOUD_DOCUMENTS_ROOT:./data/documents}

server:
  tomcat:
    max-part-count: -1
    max-part-header-size: -1
