spring:
  application:
    name: backend

  datasource:
    url: jdbc:sqlite:${ASSOINCLOUD_DB_PATH:./data/assoincloud.db}
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    locations: classpath:db/migration

  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB

assoincloud:
  password: ${ASSOINCLOUD_PASSWORD:}
  pec:
    host: ${ASSOINCLOUD_PEC_HOST:}
    port: ${ASSOINCLOUD_PEC_PORT:993}
    username: ${ASSOINCLOUD_PEC_USERNAME:}
    password: ${ASSOINCLOUD_PEC_PASSWORD:}
    ssl: ${ASSOINCLOUD_PEC_SSL:true}
    ssl-trust-all: ${ASSOINCLOUD_PEC_SSL_TRUST_ALL:false}

server:
  tomcat:
    max-part-count: -1
    max-part-header-size: -1
